#!/usr/bin/env ruby

require 'football'
require 'thor'

class FootballCLI < Thor
  option :countries, :type => :array
  desc "download", "Download an entire country or countries. Downloads all if none specified."
  def download
    Football::CSVDownloader.download(options)
  end

  desc "combine", "Combine all CSV files into one file."
  def combine
    Football::CSVCombiner.combine
  end

end

FootballCLI.start(ARGV)
