#!/usr/bin/env ruby

require 'kickme'
require 'thor'

class KickmeCLI < Thor
  option :countries, :type => :array
  option :leagues, :type => :array
  option :seasons, :type => :array
  desc "download", "Download an entire country or countries. Downloads all if none specified."
  def download
    Kickme::CSVDownloader.download(options)
  end

  desc "combine", "Combine all CSV files into one file."
  def combine
    Kickme::CSVCombiner.combine
  end

end

KickmeCLI.start(ARGV)
